server.port: 9090

spring:
  application.name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb
    username: bloguser
    password: 12345


logging:
  level:
    org:
      thymeleaf: DEBUG
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE