server.port: 9090

spring:
  application.name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb
    username: bloguser
    password: 12345
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true
    hibernate.ddl-auto: none
  sql.init:
    data-locations: classpath:/data.sql
    mode: always


logging.level:
    org:
      hibernate:
        SQL: INFO
        type.descriptor.sql.BasicBinder: TRACE